services:
  # XXX networks/links
  prometheus:
    container_name: prometheus
    read_only: true
    ports:
    - '9090:9090'
    build:
      context: .
      dockerfile: prometheus.Dockerfile
    deploy:
      resources:
        limits:
          memory: 512M
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--storage.tsdb.path=/prometheus'
    volumes:
    - type: volume
      source: prometheus-data
      target: /prometheus
    links:
    - thanos
  minio:
    container_name: minio
    read_only: true
    ports:
    - '9000:9000'
    - '9091:9091'
    image: quay.io/minio/minio
    deploy:
      resources:
        limits:
          memory: 512M
    command:
    - server
    - /data
    - --console-address
    - ':9091'
    env_file: minio.env
    volumes:
    - type: volume
      source: minio-data
      target: /data
    - type: tmpfs
      target: /root
  thanos:
    container_name: thanos
    read_only: true
    ports:
    - '10907:10907'
    - '10909:10909'
    image: quay.io/thanos/thanos:v0.29.0
    build:
      context: .
      dockerfile: thanos.Dockerfile
    deploy:
      resources:
        limits:
          memory: 512M
    command:
    - receive
    - '--tsdb.path'
    - /data
    - '--grpc-address'
    - '0.0.0.0:10907'
    - '--http-address'
    - '0.0.0.0:10909'
    - '--receive.replication-factor'
    - '1'
    - '--label'
    - 'receive_replica="0"'
    - '--label'
    - 'receive_cluster="eu1"'
    - '--receive.local-endpoint'
    - '127.0.0.1:10907'
    - '--remote-write.address'
    - '0.0.0.0:10908'
    - '--objstore.config-file'
    - 'objstore.yml'
    volumes:
    - type: volume
      source: thanos-data
      target: /data
    links:
    - minio

volumes:
  prometheus-data:
    driver_opts:
      type: tmpfs
  minio-data:
  thanos-data:
