services:
  # XXX networks/links
  prometheus:
    container_name: prometheus
    read_only: true
    ports:
    - '9090:9090'
    build:
      context: .
      dockerfile: prometheus.Dockerfile
    deploy:
      resources:
        limits:
          memory: 512M
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--storage.tsdb.path=/prometheus'
    volumes:
    - type: volume
      source: prometheus-data
      target: /prometheus
  minio:
    container_name: minio
    read_only: true
    ports:
    - '9000:9000'
    - '9091:9091'
    image: quay.io/minio/minio
    deploy:
      resources:
        limits:
          memory: 512M
    command:
    - server
    - /data
    - --console-address
    - ':9091'
    env_file: minio.env
    volumes:
    - type: volume
      source: minio-data
      target: /data
    - type: tmpfs
      target: /root

  # XXX thanos

volumes:
  prometheus-data:
    driver_opts:
      type: tmpfs
  minio-data:
