apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: grafana
  name: grafana
spec:
  serviceName: grafana
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana
    spec:
      containers:
      - name: main
        image: grafana/grafana:10.1.2
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: storage
          mountPath: /var/lib/grafana
      volumes:
      - name: storage
        # XXX change me later!
        emptyDir: {}
