apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: loki
  name: loki
spec:
  serviceName: loki
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
  template:
    metadata:
      labels:
        app.kubernetes.io/name: loki
    spec:
      containers:
      - name: main
        image: grafana/loki:2.9.1
        imagePullPolicy: IfNotPresent
        args:
        - '-config.file=/etc/loki/loki.yml'
        volumeMounts:
        - name: data
          mountPath: /loki
        - name: config
          mountPath: /etc/loki
      volumes:
      - name: data
        # XXX change me later!
        emptyDir: {}
      - name: config
        configMap:
          name: loki-config
