apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: loki
  name: loki
spec:
  serviceName: loki
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
  template:
    metadata:
      labels:
        app.kubernetes.io/name: loki
    spec:
      containers:
      - name: main
        image: grafana/loki:2.9.1
        imagePullPolicy: IfNotPresent
        args:
        - '-config.file=/etc/loki/loki.yml'
        volumeMounts:
        - name: data
          mountPath: /loki
        - name: config
          mountPath: /etc/loki
      securityContext:
        fsGroup: 2000
      volumes:
      - name: config
        configMap:
          name: loki-config
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
