apiVersion: v1
kind: ConfigMap
metadata:
  namespace: loki
  name: loki-config
data:
  loki.yml: |-
    auth_enabled: false

    server:
      http_listen_port: 3100
      grpc_listen_port: 9096

    common:
      path_prefix: /loki
      replication_factor: 1
      storage:
        filesystem:
          chunks_directory: /loki/chunks
          rules_directory: /loki/rules
      ring:
        kvstore:
          store: inmemory

    query_range:
      results_cache:
        cache:
          embedded_cache:
            enabled: true
            max_size_mb: 100

    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h

    frontend:
      log_queries_longer_than: -1
