apiVersion: v1
kind: ConfigMap
metadata:
  namespace: loki
  name: promtail-config
data:
  promtail.yml: |-
    server:
      http_listen_port: 9080
    positions:
      filename: /var/lib/promtail/positions.yaml
    clients:
    - url: http://loki.loki.svc.cluster.local:3100/loki/api/v1/push
    scrape_configs:
    - job_name: kubernetes-services
      kubernetes_sd_configs:
      - role: endpoints
      relabel_configs:
      - action: labelmap
        source_labels: [__meta_kubernetes_pod_node_name]
        target_label: __host__
      - action: replace
        replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
          - __meta_kubernetes_pod_uid
          - __meta_kubernetes_pod_container_name
        target_label: __path__
      - action: labelmap
        regex: "__meta_kubernetes_(namespace|pod_name|pod_container_port_name|service_port_name)"
        replacement: "$1"
