apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: prometheus
  name: prometheus
spec:
  serviceName: prometheus
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus
    spec:
      serviceAccountName: prometheus
      containers:
      - name: main
        image: prom/prometheus:v2.47.0
        imagePullPolicy: IfNotPresent
        args:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        volumeMounts:
        - name: tsdb
          mountPath: /prometheus
        - name: config
          mountPath: /etc/prometheus
      volumes:
      - name: tsdb
        # XXX change me later!
        emptyDir: {}
      - name: config
        configMap:
          name: prometheus-config
