apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: loki
  name: promtail
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: promtail
  template:
    metadata:
      labels:
        app.kubernetes.io/name: promtail
    spec:
      serviceAccount: promtail
      containers:
      - name: main
        image: grafana/promtail:2.9.1
        args:
        - '-config.file=/etc/promtail/promtail.yml'
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: 'spec.nodeName'
        volumeMounts:
        - name: config
          mountPath: /etc/promtail
        - name: positions
          mountPath: /var/lib/promtail
        - name: containers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: pod-logs
          mountPath: /var/log/pods
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: promtail-config
      - name: positions
        # XXX change me later!
        emptyDir: {}
      - name: containers
        hostPath:
          path: /var/lib/docker/containers
      - name: pod-logs
        hostPath:
          path: /var/log/pods
