apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-scrape
rules:
- verbs:
  - GET
  nonResourceURLs:
  - '/metrics*'
- apiGroups: ['']
  resources:
  - endpoints
  - nodes
  - nodes/metrics
  - pods
  - services
  verbs: ['get', 'list', 'watch']
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: prometheus
  name: prometheus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-scrape
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-scrape
subjects:
- kind: ServiceAccount
  namespace: prometheus
  name: prometheus
