kind: Namespace
apiVersion: v1
metadata:
  name: time-waster
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: time-waster
  namespace: time-waster
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: time-waster
  template:
    metadata:
      labels:
        app.kubernetes.io/name: time-waster
    spec:
      containers:
      - name: main
        image: sleep-and-waste-time
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6060
          name: http-pprof
        - containerPort: 6060
          name: http-metrics
---
kind: Service
apiVersion: v1
metadata:
  name: time-waster
  namespace: time-waster
spec:
  selector:
    app.kubernetes.io/name: time-waster
  ports:
  - name: http-pprof
    port: 6060
    targetPort: http-pprof
  - name: http-metrics
    port: 6061
    targetPort: http-metrics
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: time-waster
  namespace: time-waster
spec:
  policyTypes:
  - Ingress
  podSelector: {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: prometheus
